[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Build processing and optimization
# Content-Security-Policy header added for security
[build.processing]
  skip_processing = true

# Disabled individual asset processing overrides since skip_processing=true disables them
# [build.processing.css]
#   bundle = true
#   minify = true
# 
# [build.processing.js]
#   bundle = true
#   minify = true
# 
# [build.processing.html]
#   pretty_urls = true
# 
# [build.processing.images]
#   compress = true

# Asset optimization
# Disabled Netlify sitemap plugin to use manual sitemap.xml from public folder
# [[plugins]]
#   package = "@netlify/plugin-sitemap"

# Headers for performance optimization
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    # Allow FontAwesome CDN for styles and fonts
    Content-Security-Policy = "default-src 'self'; style-src 'self' https://cdnjs.cloudflare.com; font-src 'self' https://cdnjs.cloudflare.com; img-src * data:; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com;"
    
    # SEO and crawling
    Access-Control-Allow-Origin = "*"
    X-Robots-Tag = "all"
    
    # Enable compression detection
    Vary = "Accept-Encoding"
    
    # Default caching for HTML with proper Expires header
    Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"
    Expires = "Thu, 31 Dec 2025 23:59:59 GMT"

# CSS and JS assets - Long-term caching
[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Thu, 31 Dec 2025 23:59:59 GMT"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/assets/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Thu, 31 Dec 2025 23:59:59 GMT"
    Vary = "Accept-Encoding"

# Long-term caching for hashed assets
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Thu, 31 Dec 2025 23:59:59 GMT"
    Vary = "Accept-Encoding"

# Images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Thu, 31 Dec 2025 23:59:59 GMT"

# Fonts with CORS
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
    Expires = "Thu, 31 Dec 2025 23:59:59 GMT"

# FontAwesome CDN CORS headers
[[headers]]
  for = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

# Additional font formats
[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
    Expires = "Thu, 31 Dec 2025 23:59:59 GMT"

[[headers]]
  for = "/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
    Expires = "Thu, 31 Dec 2025 23:59:59 GMT"

[[headers]]
  for = "/*.eot"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
    Expires = "Thu, 31 Dec 2025 23:59:59 GMT"

# Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirects for SEO and canonical URL enforcement
# Force HTTPS and non-www canonical domain to eliminate redirect chains
[[redirects]]
  from = "http://brightforgeseo.com/*"
  to = "https://brightforgeseo.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.brightforgeseo.com/*"
  to = "https://brightforgeseo.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.brightforgeseo.com/*"
  to = "https://brightforgeseo.com/:splat"
  status = 301
  force = true

# Internal page redirects
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
