[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "/404/"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/bright-forge-seo/*"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/bright-forge-seo"
  to = "/"
  status = 301
  force = true
